spring:
  cloud:
    function:
      definition: publishConfirmationConsumer
    stream:
      bindings:
        publishConfirmationConsumer-in-0:
          destination: 'publish/topic/test'
          group: clientAck
        publishConfirmationConsumer-out-0:
          destination: 'publish/topic/success'
          producer:
            error-channel-enabled: true
      binders:
        solace-broker:
          type: solace
          environment:
            solace: # (1)
              java:
                host: tcp://localhost:55554
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: -1
                reconnectRetries: -1

